INSERT INTO "region" ("region_name") VALUES
  ('Zakarpats''ka oblast'),
  ('Lviv Oblast'),
  ('Ivano-Frankivs''ka oblast'),
  ('Volyns''ka oblast'),
  ('Rivnens''ka oblast'),
  ('Ternopil''s''ka oblast'),
  ('Chernivets''ka oblast'),
  ('Khmel''nyts''ka oblast'),
  ('Zhytomyrs''ka oblast'),
  ('Vinnyts''ka oblast'),
  ('Kyivs''ka oblast'),
  ('Cherkas''ka oblast'),
  ('Kirovohrads''ka oblast'),
  ('Odessa Oblast'),
  ('Mykolaivs''ka oblast'),
  ('Chernihivs''ka oblast'),
  ('Sums''ka oblast'),
  ('Poltavs''ka oblast'),
  ('Dnipropetrovsk Oblast'),
  ('Khersons''ka oblast'),
  ('Crimea'),
  ('Kharkiv Oblast'),
  ('Zaporiz''ka oblast'),
  ('Donetsk Oblast'),
  ('Luhans''ka oblast');
